#server
server:
  port: 8089
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql://10.8.37.81:3306/firstnews?serverTimezone=GMT%2b8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false


#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/news/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG
    
#Thread rool
async-thread-pool:
  corePoolSize: 5
  maximumPoolSize: 10
  keepAliveTime: 30
         
    
    
    
    
    
    